name: The Art of Erik Égon
favicon: null
layout_spectrum: 0.15428854920901358
typography_spectrum: 0.22536141145974398
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.9924999962095171
  lightness: 0.8814864722080529
  saturation: 0.6518650376237929
  rhythmicContrast: 0.6007618112489581
purpose: []
