name: The Art of Erik Égon
favicon: null
layout_spectrum: 0.64284
typography_spectrum: 0.09169
title: The Art of Erik Égon
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#302a24'
    - '#ff6b01'
    - '#9c9895'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
